### ISSUE TITLE
Pretty shell option

### ISSUE THREAD

**Issue by MadLittleMods** [MadLittleMods/linux-notes#35]
Bash shell alternative where we can do nice pretty things.

First figure out your terminal emulator: https://github.com/MadLittleMods/linux-notes/issues/30

### Solution

TBD

Interesting options:

 - https://starship.rs/
 - Zsh and Oh My Zsh

**Comment by MadLittleMods** [comment]
I've been using this terminal/prompt for a little while now:

 - [ghostty](https://github.com/ghostty-org/ghostty) terminal (default theme which is a modified Tomorrow Night)
     - Ghostty ANSI colors for reference: [`ghostty-org/ghostty` -> `src/terminal/color.zig#L48-L94
`](https://github.com/ghostty-org/ghostty/blob/4853597cd9829e622be2c3628dc748407c27c423/src/terminal/color.zig#L48-L94)
 - zsh shell (doesn't matter, could be bash)
 - [oh-my-posh](https://ohmyposh.dev/) theming for the prompt (custom theme based on Agnoster)

Inspired to actually update my prompt after seeing this video (Dreams of Code): https://www.youtube.com/watch?v=9U8LCjuQzdc

![](https://github.com/user-attachments/assets/96363b99-46d4-421c-9b9a-0e7d9b0a1af2)


Add to your `.zshrc`:

```sh
# eric: for oh-my-posh (prompt theme)
eval "$(oh-my-posh init zsh --config $HOME/.config/oh-my-posh/eric.toml)"
```

Config:

<details>
<summary><code>~/.config/oh-my-posh/eric.toml</code></summary>

```toml
version = 2
final_space = true


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    background = 'transparent'
    foreground = 'white'
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}({{ .Venv }}) {{ end }}{{ end }}'

    [blocks.segments.properties]
      display_mode = 'environment'
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .UserName }}@{{ .HostName }} '
    background = 'white'
    foreground = '#100e23'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = ' {{ .Path }} '
    background = 'blue'
    foreground = '#100e23'

    [blocks.segments.properties]
      folder_separator_icon = '  '
      home_icon = ''
      style = 'agnoster_short'
      max_depth = 3

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    background = 'green'
    foreground = '#193549'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      branch_max_length = 50
      truncate_symbol = '...'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    template = ' {{ .CurrentDate | date .Format }} '
    foreground = 'blue'

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 0


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'
```
